### ISSUE TITLE
High-level structure for Polymer (base elements, inheritance structure, folder structure, in-app routing library)

### ISSUE THREAD

**Issue by wkronmiller** [RPISDD/Documentation#12]
Time Required: 20 person-hours

**Comment by wkronmiller** [comment]
https://divshot.com/blog/web-components/polymer-app-structure-tips/

**Comment by wkronmiller** [comment]
https://pascalprecht.github.io/2014/07/14/inheritance-and-composition-with-polymer/

**Comment by wkronmiller** [comment]
https://github.com/basic-web-components/components-dev/wiki/Ten-Principles-for-Great-General-Purpose-Web-Components

**Comment by wkronmiller** [comment]
https://www.youtube.com/watch?v=1f_Tj_JnStA

**Comment by MalcolmLorber** [comment]
Closed, see #18 #19.
