### ISSUE TITLE
High level structure for Node.JS

### ISSUE THREAD

**Issue by MalcolmLorber** [RPISDD/Documentation#15]

**Comment by wkronmiller** [comment]
Trivial example of using objects and converting them to JSON

> var friend = {UID: 1, Classes: [1,2,3]}
> undefined
> var friends = [friend, friend]
> undefined
> JSON.stringify(friends)
> '[{"UID":1,"Classes":[1,2,3]},{"UID":1,"Classes":[1,2,3]}]'

**Comment by wkronmiller** [comment]
http://imgur.com/Oj3g4eh

**Comment by wkronmiller** [comment]
@MalcolmLorber Could you send me what you've got, when you have a sec? Thanks!
