### ISSUE TITLE
Polymer inheritance

### ISSUE THREAD

**Issue by MalcolmLorber** [RPISDD/Documentation#19]

**Comment by wkronmiller** [comment]
http://www.html5rocks.com/en/tutorials/webcomponents/yeoman/

**Comment by wkronmiller** [comment]
http://www.html5rocks.com/en/tutorials/webcomponents/yeoman/

**Comment by wkronmiller** [comment]
We can use nesting and access/manipulate "parent" element, Not true inheritance, but still declarative/imperative with objects. It's also best practice, from what I can tell.

**Comment by wkronmiller** [comment]
https://github.com/RPISDD/Documentation/wiki/Polymer
