### ISSUE TITLE
Deployment Diagram

### ISSUE THREAD

**Issue by ChuckJKelly** [RPISDD/Documentation#23]
Provide a diagram that is representative of the hardware and software platform(s) used to deploy your solution. Please include descriptions of all required hardware and software and justification for your choices. Proper UML notation is required.

**Comment by wkronmiller** [comment]
Needs version numbers for software.

**Comment by wkronmiller** [comment]
"You can hand it to anybody, and they can develop it"

**Comment by chb777777** [comment]
I'm working on this now.

**Comment by chb777777** [comment]
are we sticking with the stack with polymer
