### ISSUE TITLE
Full-stack integration tested

### ISSUE THREAD

**Issue by wkronmiller** [RPISDD/Documentation#30]
Polymer to Node.JS to DynamoDB
Time Required: 2-10 person-hours

**Comment by ChuckJKelly** [comment]
I don't know what this is

**Comment by wkronmiller** [comment]
Write a toy Polymer app to talk to NodeJS in Lambda. The NodeJS should change/read something in DynamoDB.

**Comment by ChuckJKelly** [comment]
k

**Comment by wkronmiller** [comment]
Done by Malcolm
